### ISSUE TITLE
File Permissions of the source files should be honored

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#13]
I do not have time at the moment to check the code, but I want to leave it as an issue to be checked later: Pina Golada should honour the file permission of the files it reads from disk as they are. When extracting, do not apply any hard-coded permission but rather restore the exact file permissions from when it was persisted.

**Comment by LynxPlay101** [comment]
Fixed in #12. Somewhat, for now this allows to set the permission from the extracting code.

**Comment by LynxPlay101** [comment]
I will release v1.2 soonish. I didn't think you would be online, but I guess you can now at least review the pr to master

**Comment by LynxPlay101** [comment]
Right now we kinda have the issues that most files still get assigned a 0700 when created. I still believe this is somewhat reasonable but we could technically feed the permission of a file to it's parent if it doesn't have its own yet

**Comment by HeavyWombat** [comment]
Frankly, a default permission `0700` is something I dislike. Making the file executable even though it might just be a source code file is something I consider bad practice. Basically any default file permission you pick is wrong. Preserving the file permission of the input file is the best option. Tarballs support preserving file permissions, so this is the way to go.

If, there is ever no way out, consider a default of `0644` or `0640` as a better default file permission setting. But even then, I would always try to guess a better file permission based on the magic code of the file. Tools like `file` are of great help to guess the content of a file.

**Comment by LynxPlay101** [comment]
Yeah exactly. The point is that we can easily retrieve the file permission. I would rather have the user be able to directly decide what permission the files need. The directories are currently the issue
