### ISSUE TITLE
Generated source file may include duplicate import statements

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#27]
**Describe the bug**
If you configure pina-golada to have two separate directory assets, you end up with a Go source file with two identical import statements. The Go compiler will break at this point.

**To Reproduce**
Use two insertion points with directories:
```
	// @pgl(asset=../../../assets/tests/issue-tbd/directory-1&compressor=tar)
	GetInfoFileNo1() (d files.Directory, err error)

	// @pgl(asset=../../../assets/tests/issue-tbd/directory-2&compressor=tar)
	GetInfoFileNo2() (d files.Directory, err error)
```

**Expected behavior**
Generated Go source file should be generated with a correct import path section.

**Comment by LynxPlay101** [comment]
This is fixed by #28
