### ISSUE TITLE
File permissions are not preserved correctly

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#35]
**Describe the bug**
When using the `tar` compressor, it seems the file permissions are not preserved for directories when compressing and decompressing.

**To Reproduce**
A branch with an example will follow.

**Expected behavior**
File permissions are correctly preserved when compressing and restored when decompressing.

**Comment by HeavyWombat** [comment]
@LynxPlay101 I suspected the compressor to be the root cause of the issues I see in `gonut`, so I decide to write a test case that reproduces the issues we see.

You can checkout the [`bugfix/directory-permission` branch](https://github.com/homeport/pina-golada/tree/bugfix/directory-permission) to see the failing test case. The problem is that the directories that are decompresses seem to end with a file permission of `0`.

**Comment by LynxPlay101** [comment]
Interesting. I will look into the golang implementation pina-golada is using for tar

**Comment by LynxPlay101** [comment]
Was this the issue we talked about on slack ?

**Comment by HeavyWombat** [comment]
Thanks for looking into it.
