### ISSUE TITLE
Add verbose mode

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#38]
**Is your feature request related to a problem? Please describe.**
Not a problem, just a lack of user feedback when running `pina-golada`.

**Describe the solution you'd like**
Add a new flag called `--verbose` or similar to print a bit of statistics during generate and cleanup. For the generate part, I would suggest to print a brief summary (only a couple of lines) of which files where compressed into what size in the final source code. The cleanup command could show the files that are about to be deleted.

**Describe alternatives you've considered**
_not applicable_

**Additional context**
_not applicable_

**Comment by LynxPlay101** [comment]
This issue has been fixed by #46
