### ISSUE TITLE
Spike: Evaluate whether Go style build tags could be used

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#39]
At the moment, the annotations are influenced by how Java would add annotations for functions or fields. Even though this is fine and it works, I would suggest to look into an investigation to switch the annotations to a more Golang look and feel. One source of inspiration would be the [Go build tags](https://golang.org/pkg/go/build/): `// +build linux,386 darwin,!cgo`.

**Comment by LynxPlay101** [comment]
The annotation system of pina-golada already allows to different annotation parsers to be used. 
We could either pass the requested parser as a command flag or define it on the interface comment.

**Comment by LynxPlay101** [comment]
After looking into this a bit futher, the golang tags are unfortunatly only tags. They do not pass data in any way added to the tags, only lables that are either inverted or not.

We could think about something like
// +pgl asset,/my/weird/asset/path & compressor,tar.

Opinion on that format @HeavyWombat

**Comment by LynxPlay101** [comment]
This is adressed by #53
