### ISSUE TITLE
Overhaul README and/or documentation

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#40]
One of the nice side effects of writing [`gonut`](https://github.com/homeport/gonut) was to get a feeling on how to use `pina-golada` in a project, both in terms of the Go part as well as the integration into an automated build.

I would suggest to rework and overhaul the README and descriptions to be more friendly for first time users. Although it is technically correct what has been written, it is hard to read when using it the first time.

Once I find some free time, I would like to tackle this one and provide a PR for review.

**Comment by LynxPlay101** [comment]
Yes, as I am not too profound when it comes to writing high quality README.md files, I would approciate someone else to work on this.

**Comment by LynxPlay101** [comment]
When adressing this issue, the issue #42 should also be fixed.

**Comment by LynxPlay101** [comment]
Fixed by #48
