### ISSUE TITLE
Add curl-style install to README

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#42]
Add a section in the README and explain the installation option via downloaded install script. The following code works and should be used as the example:

```sh
curl -fsL https://ibm.biz/Bd2645 | bash
```

**Comment by LynxPlay101** [comment]
Shouldn't we do the same thing as in all other homeport projects and use the download-latest file in the master branch ?

**Comment by HeavyWombat** [comment]
The URL `https://ibm.biz/Bd2645` resolves to the download latest script in the master branch.

**Comment by LynxPlay101** [comment]
When adressing this issue, concider adressing it while fixing #40

**Comment by LynxPlay101** [comment]
This was fixed by #48
