### ISSUE TITLE
Create a logo

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#44]
I think it is also time to think about a logo for this project, and t-shirts of course. I would really appreciate if someone comes up with logo ideas.

**Comment by LynxPlay101** [comment]
The logo is a great idea 😂 I am not too sure about the t-shirts 😉

**Comment by LynxPlay101** [comment]
![pina-golada](https://user-images.githubusercontent.com/32834385/54932256-c71fba00-4f1a-11e9-98d1-d7ac6ed2c858.png)

This immage was suggested by [lecim](https://github.com/lecim)

**Comment by HeavyWombat** [comment]
It is weird enough that I like it.

**Comment by LynxPlay101** [comment]
Nice 😊 I'd say we use it. Any clue on how to add it to the GitHub project or is it just linked in the readme

**Comment by LynxPlay101** [comment]
Fixed by #47 and #48
