### ISSUE TITLE
Fix staticcheck/golint findings

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#55]
There seems to be an updated version of a tool I used to use to statically check my Go source code: https://github.com/dominikh/go-tools

Luckily, `pina-golada` is already pretty good in that respect, but a couple of findings were found. This is something we could fix:
> internal/golada/cmd/generate.go:42:19: should use raw string (`...`) with regexp.MustCompile to avoid having to escape twice (S1007)
> pkg/files/directory.go:181:2: redundant return statement (S1023)
> pkg/files/directory.go:270:2: redundant return statement (S1023)
> pkg/files/files_test.go:66:10: should use buffer.String() instead of string(buffer.Bytes()) (S1030)

Furthermore, the [Go Report Card](https://goreportcard.com/report/github.com/homeport/pina-golada) gives us a couple of more linter findings:
> pina-golada/pkg/annotation/property_parser.go
> Line 66: warning: redundant if ...; err != nil check, just return error instead. (golint)
>
> pina-golada/pkg/annotation/csv_parser.go
> Line 65: warning: redundant if ...; err != nil check, just return error instead. (golint)
>
> pina-golada/pkg/annotation/label_parser.go
> Line 65: warning: redundant if ...; err != nil check, just return error instead. (golint)

**Comment by LynxPlay101** [comment]
This issue was fixed by #56
