### ISSUE TITLE
Use full semver versions

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/pina-golada#57]
Go modules are very picky when it comes to version numbers. For example, the current version `v1.3` is not recognised as a usable version for Go modules:

```
go: errors parsing go.mod:
$GOPATH/src/github.com/homeport/gonut/go.mod:5: invalid module version "v1.3": no matching versions for query "v1.3"
```

To be able to use it, we would need a new release called `v1.3.0`.

**Comment by LynxPlay101** [comment]
Interesting :/ I'll create a new release. For that matter listed as v.1.3.1 as it contains small adjustments to improve the go report card 👍

**Comment by LynxPlay101** [comment]
https://github.com/homeport/pina-golada/releases/tag/v1.3.1
